services:
  proxy:
    build: ./proxy
    ports:
      - 80:80
    depends_on:
      - api
      - spa
  api:
    build: ./backend
    ports:
      - 8080:8080
    environment:
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    depends_on:
      - db
  spa:
    build: ./frontend
    ports:
      - 3000:3000
  db:
    build: ./db
    ports:
      - 3306:3306
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - ~/data:/var/lib/mysql